### ISSUE TITLE
SQL error "field doesn't have a default value" on mysql 5.7

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/geneloader#6]
Using:

    $ mysql -V
    mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

I get the following error. This seems to be related with 5.7 default sql mode with [STRICT_TRANS_TABLES](https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_strict_trans_tables) enabled.

geneloader.1.php returned error in code block Unknown.<BR>Query : INSERT INTO lovd_genes (`id`, `name`, `chromosome`, `chrom_band`, `refseq_genomic`, `refseq_UD`, `id_hgnc`, `id_entrez`, `id_omim`, `created_by`, `created_date`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)<BR>Error : Error in PDOStatement::execute() while executing prepared query: SQLSTATE[HY000]: General error: 1364 Field 'reference' doesn't have a default value

**Comment by mkroon1** [comment]
Looking at this in more detail, it's probably best solved by defining a default value for field `reference` in the genes table in project [LOVDnl/LOVD3](https://github.com/LOVDnl/LOVD3).

**Comment by ifokkema** [comment]
Closing this as it's solved in upstream LOVD.
